CREATE TABLE IF NOT EXISTS TEST_TABLE(
    ID INTEGER AUTO_INCREMENT,
    CHAR_COL CHARACTER(1),
    VARCHAR_COL VARCHAR(250),
    TINYINT_COL TINYINT,
    SMALLINT_COL SMALLINT,
    INTEGER_COL INTEGER,
    BIGINT_COL BIGINT,
    NUMERIC_COL NUMERIC(10, 2),
    REAL_COL REAL,
    DOUBLE_COL DOUBLE,
    DATE_COL DATE,
    TIME_COL TIME,
    TIMESTAMP_COL TIMESTAMP,
    PRIMARY KEY (ID)
);